vince-fugnitto/local-history-ext

.eslintrc.json
.gitignore
package.json
src/extension.ts
src/local-history.ts

Finish: #1 
- create local history quick-pick command, and editor context-item
- save the content of the current editor at the given timestamps
- quick-pick now displays the filename, timestamps and file path of the history files for the current editor
- user can now select an item in the listing and open the older version of file in a new editor
- When user attempts to view local history for an active editor that does not belong to a workspace folder, a message is shown.
- When no local history is available for an active editor, a message is shown.
- Create a new file
- Right click in the active editor and sellect `Local …

Completes User Story 1

---

src/extension.ts
src/local-history.ts

- Load all local history file entries on activation
- Refactor code for generating timestamp
- Right click in the active editor and sellect `Local History: Local History: Active Editor`

Load history files on activation and code refactor

---

src/local-history.ts

Completes: #7 
- User can now view a local history save as a diff compared to the current active editor and clearly identify the differences between two revisions.
- Select a local history file to view the diff

Display the previous save as a diff

---

src/local-history.ts

Completes: #12 
- Display the timestamp in a more readable format
- Sort the entries by newest first

Improve display of entries

---

package.json
src/extension.ts
src/local-history.ts

[Preference]: add a preference to control the number of entries to keep for a file
Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/5
Added preference to control the number of revisions to store from the
most recent one, the revisions are not deleted so if at any point the
user tends to change it to a larger number, the older ones will show up.
How to Test: 
- Go to File on top menu and select Add Folder to Workspace
- Create a new file inside the src folder
- Open file>preferences>settings>extensions>local History
- Change the value of the max file revisions
- Open the Command Palette (Ctrl+Shift+P), enter Local History: Local History: Active Editor
All this process of …

preference: add a preference to control the number of entries of revisions

---

src/local-history/local-history-manager.ts

Fix: #23 
- When opening a local history file from the quickPick menu, retrieve the file uri from `selection.description`
- Right click in the active editor to trigger  the editor's context menu and select  `Local History: Active Editor`
- Select a local history file to view the diff

Retrieve file uri from selection.description

---

package.json

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/22
Currently in master, the command `Local History: Active Editor` was
visible for any file opened, and even without any editors opened. Added
functionality to tackle this situation, and handle the command when
there is an editor opened.
How to Test:
1. open a workspace (without any files)
2. press F1 and search for local history
3. see that the command is not available with no editors opened, and available with an editor opened with a file from the filesystem.

[Command]: Command should respect an active/preview editor

---

package.json
src/extension.ts
src/local-history/local-history-manager.ts

- Add a `Clock icon` in the top right menu in diff mode
- When user click the `Clock icon`, Display pop-up message asking the user to confirm the reversion
- If `Revert` is selected, the active editor will be reverted to its previous revision
- Right click in the active editor to trigger  the editor's context menu and select  `Local History: Active Editor`
- Select a local history file to view the diff
- Click the `Clock icon` in the top right menu when in diff mode
Signed-off-by: Kaiyue Pan …

Revert active editor to its previous state

---

package.json
src/extension.ts
src/local-history/local-history-manager.ts

- Add a  `Trash icon` in diff-mode
- Display pop-up message asking the user to confirm the deletion
- If `Delete` is selected, the current active revision of a file will be deleted
- Fix `File is not a revision` error on Windows
- Right click in the active editor to trigger  the editor's context menu and select  `Local History: Active Editor`
- Select a local history file to view the diff
- Click the `Trash icon` in the top right menu when in diff mode
Signed-off-by: Kaiyue Pan …

Remove a revision through the UI

---

package.json
src/extension.ts

- Remove `Revert to Previous Revision` and `Remove Revision` from command palette since
1. they do not function properly
2. it is redundant to keep them (they already exist in the navigator in diff mode)
1. Open a file inside a workspace
2. Open the Command Palette (`Revert to Previous Revision` and `Remove Revision` should no longer be there)

Remove commands from command palette

---

package.json
src/extension.ts
src/local-history/local-history-manager.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/37
**What it does**
Creates a .local-history folder in the home directory of the user,
it then also hashes the file uri and creates folder on each uri.
Currently it is stored in each workspace.
1. Add a new folder to the workspace
2. Save something on an active editor 
4. Go to your local home directory
5. navigate to .local-history
6. Check to see if there exists a folder name with hashcode
7. Open the folder to see if there are revisions.
8. Open the Command Palette (Ctrl+Shift+P), enter Local History: Local History: Active Editor
9. Right click in the active editor to trigger the editor's context menu and select Local History: Active Editor
10. Select a local history file to view the diff
11. Click the …

Save and retrieve local history under the user's home

---

package.json
src/extension.ts
src/local-history/local-history-manager.ts

- User can now clear the local history for the active editor through
1. the command palette
2. the explorer's context menu
3. editor's context menu
1. Press f5 to enter debug mode
2. Add a folder to the workspace
3. Add content to a file and save it
4. Repeat step 3
5. Clear all local history for the active file using the command palette (when there is an active editor)
6. Clear all local history for the active file using the explorer's context menu
7. Clear all local history for the active editor using the editor's context menu

Clear all local history for the active file

---

package.json
src/extension.ts
src/local-history/local-history-manager.ts

- Add explorer context menu to trigger history for selected file
- Update title for `View History` and `Clear History`
**_- When there is no active editor:_**
2. Right click on a file in the explorer
3. Select `Local History: View History` in the explorer context menu
4. Open the command and search for `Local History: View History` (**should not exist**)
**_- When there is an active editor:_**
2. Right click on a file in the explorer
3. Select `Local History: View History` in the explorer context menu
4. Open the command and search for `Local History: View History`
5. Right click on the active editor to trigger the editor context menu and select `Local History: View History`
Signed-off-by: Kaiyue Pan …

Add `View History` to explorer context menu

---

package.json
src/extension.ts
src/local-history/local-history-manager.ts

- Hide the `Revert` and `Remove revision` icons in split view
**In split view:**
**Not in split view:**
- Refactor code for remove revision for consistency
- Makes changes to a file
- Right click in the active editor to trigger  the editor's context menu and select  `Local History: Active Editor`
- Select a local history file to view the diff (**should see the two icons**)
- Open another editor in split view (**should no longer see the two icons**)

Hide 'Revert' and 'Remove revision' icons in split view

---

package.json
src/local-history/local-history-manager.ts
src/local-history/local-history-preference-service.ts

Fixes: #9 
**What it does**
Works like autoSave, but for local history, after a specified interval of time, it autosaves the history file of the code. 
1. Open  a workspace
2. Go to Settings > Preferences > Local History > autoSave
3. Set a value. 
4. Make changes in your file and after every interval, it will create a new history of changes in the files are found.

preference: control save delay

---

package-lock.json
package.json
src/local-history/local-history-manager.ts

- Add relative creation time for entries in quickPick menu using momentJs
- Use older version of momentJS
1. Open a file which does not contain any local-history (clear history if required - ex: rm -rf ~/.local-history)
2. Make a change and perform a save
3. Execute the command Local History: View History (should see the `Created ... ago`)

Add relative creation time using momentJs

---

src/local-history/local-history-manager.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/62
**What it does**
Saves the file history when the file is closed to prevent loss of
content.
2. Create a new file.
3. Make changes to the file.
4. Save and close the file check to see if local history timestamp is updated on close or not.

save history when file is closed.

---

src/local-history/local-history-manager.ts

- Fix relative creation time bug when the timestamp of a revision is updated
2. Create a new file.
3. Make changes to the file and save.
4. Save again without changing the content of the file
5. The timestamp should be updated and the relative creation time should now be correct

Fix relative modification time bug

---

package.json
src/extension.ts
src/local-history/local-history-manager.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/59
**What It Does**
Clears the history which is last modified in X day, where X is decided
by the user input. This helps in clean up of the files.
**How To Test**
Prerequisite: For this PR, you need to have older modified local history files to test, else in order to test, you can reduce the variable value `dayToMilliSeconds` in order to fit your need. (you can change it to `1000` just so it could be converted into seconds, would be easier to test. )
1. Press `f1` and `Local History: Clear Old History`
2. Enter the number of days for which you want history to be deleted
3. Press enter, check to see if the history is successfully deleted inside the `.local-history` folder.
Signed-off-by: Anas Shahid …

Command to remove histories after x amount of days

---

package.json
src/local-history/local-history-manager.ts
src/local-history/local-history-preferences-service.ts
src/local-history/local-history-preferences.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/77
**What it Does**
Adds a preference which caps the maximum file size in order to create a
local history file, in the file-size od the active document is within
the boundary then it will perform a save, else it won't.
1. Open the workspace with a file size greater than the limit
2. Try to make changes and perform save
3. Check to see if the file is saved or not.
For testing, a dummy file can be used. 
[testing.txt](https://github.com/vince-fugnitto/local-history-ext/files/4626282/testing.txt)
In order to test the functionality with this test file, you can set the preference value to a lesser value than the file size, for eg `0.13` will work with this file.

preference: limit the max file size for a revision

---

package.json
src/local-history/local-history-manager.ts
src/local-history/local-history-preferences-service.ts
src/local-history/local-history-preferences.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/76
**What it Does**
This allows the user to set a limit for the number of revisions they
want for each file, it is helpful in files which are super large as it
will not flush extra storage.
It removes the oldest revision of that file and adds a new revision on
top.
`Due to the bug caused by #40, if testing is done in windows, it would be better if the user creates multiple history revisions in one host, close it, and then using a fresh host try to do the remaining steps. `
1. Open workspace
2. Make revisions up to the limit
3. Add a new revision, check to see if the total number of revisions stored are within the limit
4. Check to see if the latest save is stored as a revision
5. Check to see if the oldest …

preference: limit the number of revisions to store for a file

---

package-lock.json
package.json
src/extension.ts
src/local-history/local-history-manager.ts
src/local-history/local-history-preferences-service.ts
src/local-history/local-history-types.ts
src/test/suite/local-history-preference-service.test.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/89
This allows the user to exclude the files for which they dont want local
history of.
2. In the Preference>Local History> Excluded Files
3. Edit json file to update the files.
4. Add `"**/*.txt" : true`. 
4. Save and create a new `.txt` file
5. Make changes and save. 
6. Press `f1` and `Local History: Active Editor`
4. Check to see if the history for that source file is created

preference: support filesExclude

---

src/local-history/local-history-manager.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/87
Upon clearing the history files, if the folder is empty, it will also
remove that specific folder.
1.Open a folder in workspace
2. Create multiple revisions. 
3. (For testing purposes change the variable `DAY_TO_MILLISECONDS` inside  `local-history-types.ts` to around `5`
4. Restart the host, perform `f1` `Local History: Clear Old History`. Enter `1` day. 
5. Check to see inside `home/.local-history` if the folder exists or not. 

Remove empty folders

---

src/local-history/local-history-manager.ts
src/test/suite/local-history-manager.test.ts
src/test/suite/mock-text-document.ts

The following pull-request:
1. refactors the method name from `excludeFiles` to `isFileExcluded`
2. adds tests for `isFileExcluded` which is ultimately used to determine if the given document should have it's local-history saved, or if it is exempted due to exclude globs.

test: add tests for 'isFileExcluded`

---

README.md
package.json
src/extension.ts
src/local-history/local-history-types.ts

The following pull-request adds the new command `Local History: View Command`.
Triggering the command will open the external documentation link (repository readme section).
The documentation will be updated as part of #84 

command: add 'view documentation' command

---

src/local-history/local-history-manager.ts
src/local-history/local-history-output-manager.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/90
All the error messages will be printed directly to a seperate output
channel of Local History, this is done to not pollute the default output
channel for the user.
How to Test:
2. Create a new file.
3. Without saving press `f1` -> `Local History: View History`
4. In the integrated output channel, try selecting `Local History` and check to see if the message is logged there with the appropriate timestamp and severity.

uses output channel to display warning/errors

---

src/extension.ts
src/local-history/local-history-manager.ts

- Create a revision before reverting
- Prevent user from reverting to the same revisions more than once
- Add revision context metadata (revert change, manual change) to filenames for revisions
1. Open a file which does not contain any local-history
2. Save the file and view local history for that file (should see a revision with a filename containing _m)
3. Create 2 more revisions
4. View the first revision in diff and click the revert icon
5. After reverting, confirm that a new revision is created (the filename should contain _r)
6. Click the revert icon again (nothing should happen)

Save before revert

---

package.json
src/extension.ts
src/local-history/local-history-manager.ts
src/local-history/local-history-types.ts

- Add two new commands which end-users can use to easily locate their revisions:
1. copy revision path: adds the revision path (active editor) to the clipboard
2. copy revision path (workspace): adds the revision path (the given workspace) to the clipboard
- Update when-context for `View History` and `Clear History` commands
1. Make sure your clipboard does not have old revision path
2. Right-click on a file that has revisions and select `Copy Revision Path` (Should see the file's revision path when you paste it)
3. Select multiple files and right-click (**Should not see `Copy Revision Path`, `View History`, `Clear History`**)
4. Select 1 or no item in the explorer and right-click on the empty space below (**Should see `Copy Revision Path (Workspace)`**): …

Commands for end-users to locate their revisions

---

src/local-history/local-history-manager.ts

- Checks if a file exists before performing a statSync
**How to test:**
1. Follow these [steps](https://github.com/vince-fugnitto/local-history-ext/issues/111)

Fix statSync error on Windows

---

package.json
src/local-history/local-history-types.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/72
Added minimum values on the preferences, so that the user doesn't violate
the behavior of the preference. If the value plugged is less than the
min, it will use the default value.
- Try setting the values of preferences lower than the minimum, and check to see if they reset back to default or not 

Prevent user from violating the min/max values

---

package.json
src/extension.ts
src/local-history/local-history-tree-provider.ts

The following commit updates the 'local-history tree view' to include the following:
- adds the `iconPath` to the tree-view entries
- adds the `message` to the view displaying the active editor for clarity
_Active Editor with Results_:
<div align='left'>
</div>
_Active Editor without Results_:
<div align='left'>
</div>
_No Active Editor_:
<div align='left'>
</div>
---
_Note_: I wanted to add the revision count to the `message` but there are issues with it being asynchronous to get the value.

tree-view: update user-interface

---

src/local-history/local-history-manager.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/122
Refreshes the tree-view when a new revision is created.
**How to Test:**
1. Open workspace
2. Open a file as an active editor, toggle to the Local History Tree View tab
3. Create a new revision, check to see if the new revision shows up in the tree-view

refresh tree view when revisions created

---

src/local-history/local-history-manager.ts
src/local-history/local-history-output-manager.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/103
Logs the output channel with messages when:
1. Revisions are created
2. Revisions are deleted
3. Revision is reverted
- Follow steps [here](https://github.com/vince-fugnitto/local-history-ext/pull/19)
- Follow steps [here](https://github.com/vince-fugnitto/local-history-ext/pull/26)
- Follow steps [here](https://github.com/vince-fugnitto/local-history-ext/pull/27) 
- Follow steps [here](https://github.com/vince-fugnitto/local-history-ext/pull/44)
Open the integrated terminal, and then select the `Output Channel` and select `Local History` to see if the messages are logged in the channel.

Logs creation and deletion of revisions in the output channel

---

src/local-history/local-history-manager.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/114
Saves the content of the file when it is within the save delay timer.
**How to Test:**
1. Open a folder in workspace.
2. Create a revision.
3. Save without making any changes.
4. Save a file within the `saveDelay` timer.
5. Check to see if there is an error logged. 
6. Check to see if the revision is readonly.

Updates file content when saved within the save delay

---

package-lock.json
package.json
src/extension.ts
src/local-history/local-history-manager.ts
src/local-history/local-history.d.ts

- Remove the empty folders in a workspace revision dir recursively when:
1. we manually remove the last revision (either from the tree or diff editor menu) for an active editor
2. we clear all revisions for an active editor

Remove empty folders when revision removed from UI

---

src/local-history/local-history-manager.ts
src/local-history/local-history-tree-provider.ts

- fix the error that occurs when viewing the history for an active editor with no revisions
- prevent a revision from being created when the active editor has no content
- fix `statSync` error in `checkPermission`
- Use `OutputChannel` to display error for tree-view message
1. Create a new file in a workspace (**keep it blank**) and save (**no revision is created**)
2.  View history for the active editor (**should no longer see an error in the output channel**)

Small bug fixes

---

src/local-history/local-history-manager.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/126
Updated the code to use node fs api for reading directories.
**How to test:**
1. Run theia with the extension
2. Make changes to a file
3. Run the command by `f1` `Local History: View Revisions`
4. Check to see if the revisions are displayed.

[bug] View History command doesn't work

---

package-lock.json
package.json
src/local-history/local-history-manager.ts
src/local-history/local-history.d.ts

Fixes #125 
The following pull-request fixes the creation of the `.local-history` folder for the electron target (theia), which was caused by the following line which did not work in the version we have:
```ts
fs.mkdirSync(revisionFolderPath, { recursive: true });
```
Instead, we use `shelljs` which has the capability to create a folder structure given the full path.
**Steps to Reproduce**
1. package the extension (`vsce package`)
2. remove the local-history folder if it exists (`rm -rf ~/.local-history`)
3. add the extension to theia (electron) and test if the revisions are created
4. test the extension with theia (browser) to confirm there are no regressions

electron: fix local-history creation

---

src/local-history/local-history-manager.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/134
Removes the functionality for renaming the file when the file content is
not changed.
How to test: 
1. Create a revision
2. Save without any changes (desired behavior: no changes should be made in theia)

Remove functionality for updating filename on non-dirty save

---

src/local-history/local-history-tree-provider.ts

Fixes #137 
The following commit fixes the `tree-view` message to only reflect actual active text documents which have a `file` scheme. 
For example, when the output-view channel is opened, it should not reflect so in the tree-view anymore.
**Steps to Reproduce**
1. open an editor and make a revision
2. open the `tree-view` it should show the active editor
3. close the active editor
4. open the `local history` output channel, the tree-view should not display the output-channel as the active editor
5. there should be no error logs in the output channel

tree-view: fix message

---

package.json
src/extension.ts
src/local-history/local-history-manager.ts
src/local-history/local-history-tree-provider.ts

- Add `revert to previous revision` to local-history tree-view context-menu
- Remove `delete` and `revert` from diff editor toolbar
1. Create 2 revisions
2. Go to local-history tree-view and click the `revert` icon (**without opening the diff**; should see a `_r` revision being created)
3. Open a diff and click `revert` (should see a `_r` revision being created)
4. Pin a diff, then open another diff and click `revert` (current editor should be reverted to the highlighted revision)

Add revert to tree-view

---

package-lock.json
package.json

Fixes an incorrect `devDependency` introduced by #106 which caused the entire extension to fail.

fix 'find-remove' dependency

---

README.md

Fixes #145
- Add information about revision context metadata in the filename to the documentation
[Rendered Readme](https://github.com/vince-fugnitto/local-history-ext/blob/document-context-metadata/README.md)

Add info about revision context metadata

---

src/local-history/local-history-manager.ts
src/local-history/local-history-types.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/152
Updated the conversion of bytes to megabytes based on base 2 conversion
(1mb = 1024 bytes)
Log when file size is exceeded than what is set in the preferences.
**How to test:**
1. Change the file size limit in the preferences to 2mb
2. [testing.txt](https://github.com/vince-fugnitto/local-history-ext/files/4782911/testing.txt) Add this file in your workspace, and try saving it 
3. Check to see if in the `Local History` Output channel, a new message is logged. 
4. Try saving a file within the file-size limit(saves without failing) 

Log when file exceeds the file-size limit

---

README.md

Fixes: #156
The following adds an outline of anchor points (headers) of the readme
for easier and faster navigation of important sections.

docs: add outline to readme

---

src/local-history/local-history-preferences-service.ts
src/local-history/local-history-types.ts

Fixes: https://github.com/vince-fugnitto/local-history-ext/issues/160
Any values of the preferences below the minimum if set, will be resetted
back to default.
**How to test:**
1. Set a preference value of file size limit to less than minimum
2. Use a file larger than the minimum and less than the default size
3. Check to see if the file is being saved or not(it should be saved - ideal use case)

Reset to default if the value of the preferences are set below min

---

src/local-history/local-history-tree-provider.ts

Fixes #161 
The following pull-request updates the `tree-view` message logic to first verify if the directory exists before reading contents from it which lead to an error. The error was not harmful in any way (no reduced functionality) but the pull-request now handles it.
**Steps to Reproduce**
1. open an editor which does not contain any local-history
2. verify that the `tree-view` message is correct
3. verify that the `output channel` does not display any error messages regarding the `message`.

tree-view: improve handling of tree-view message
